This example shows how we can get the successful results of a multi-query, even though one of those queries gave us an error (which we caught in the exception). This is done via `AsyncMysqlQueryErrorResult::getSuccessfulResults`.
